name: ply-0xff07
base: core22
version: '0.2'
summary: Light-weight dynamic tracer leveraging BPF in Linux
description: |
 ply is a light-weight dynamic tracer for Linux that leverages kernel's
 BPF VM in concert with kprobes and tracepoints to attach probes to
 arbitrary points in the kernel. Most tracers that generate BPF bytecode
 are based on the LLVM based BCC toolchain. ply on the other hand has no
 required external dependencies except for libc. In addition to x86_64, 
 ply also runs on aarch64, arm, riscv64, riscv32, and powerpc. 

grade: devel
confinement: strict

parts:
  ply:
    plugin: autotools
    source: https://github.com/iovisor/ply.git
    source-type: git
    build-packages:
      - autotools-dev
      - autoconf
      - automake
      - libtool
      - yacc
      - flex
      - bison
apps:
  ply:
    command: usr/local/sbin/ply
    plugs:
      - hardware-observe
      - home
      - system-observe
      - mount-observe
      - system-trace
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
